export const _application_menu = {
    ru: {
        calendar: "Календарь",
        search: "Поиск",
        reference: "Шаблоны и категории",
        feeds: "Лента",
        reports: "Аналитика и отчеты (бета)",
        plan: "Тренировочные планы",
        season: "Планы на сезон",
        groups: "Группы",
        athletes: "Спортсмены",
        admin: "Панель администрирования",
    },
    en: {
        calendar: "Calendar",
        search: "Search",
        reference: "Templates & Categories",
        feeds: "Activity feed",
        reports: "Analytics and reports (beta)",
        plan: "Training plans",
        season: "Season plans",
        groups: "Groups",
        athletes: "Athletes",
        admin: "Admin panel",
    },
};
