export const _application_menu = {
    ru: {
        clubProfile: 'Профиль клуба',
        clubManagement: 'Члены клуба',
        clubDashboard: 'Дэшборд клуба',
        clubMethodology: 'Методология клуба',
        athletesManagement: 'Управление спортсменами',
        athletesDashboard: 'Дэшборд',
        calendar: 'Календарь',
        search: 'Поиск',
        reference: 'Шаблоны и категории',
        feeds: 'Лента',
        reports: 'Аналитика и отчеты (бета)',
        plan: 'Тренировочные планы',
        season: 'Планы на сезон',
        groups: 'Группы',
        athletes: 'Спортсмены',
        methodology: 'Методология',
        admin: 'Панель администрирования',
        staminity: 'Стаминити'
    },
    en: {
        clubProfile: 'Club profile',
        clubManagement: 'Club members',
        clubDashboard: 'Club dashboard',
        clubMethodology: 'Club methodology',
        athletesManagement: 'My athletes',
        athletesDashboard: 'My dashboard',
        calendar: 'Calendar',
        search: 'Search',
        reference: 'Templates & Categories',
        feeds: 'Activity feed',
        reports: 'Analytics and reports (beta)',
        plan: 'Training plans',
        season: 'Season plans',
        groups: 'Groups',
        athletes: 'Athletes',
        methodology: 'Methodology',
        admin: 'Admin panel',
        staminity: 'Staminity'
    }
};