export const _translateRecord = {
    ru: {
        toolbar: {
            title: "Запись",
            delete: "Удалить",
            deleteFuture: "Удалить будущие записи",
            deleteAll: "Удалить всю серию записей",
            close: "Закрыть",
            settings: "Настроить отображение",
            save: "Сохранить",
        },
        type: "Тип записи",
        restDay: "День отдыха",
        sickness: "Болезнь",
        vitamins: "Витамины",
        warning: "Проблема",
        female: "Женский цикл",
        diet: "Питание",
        bar: "Нарушение режима",
        travel: "Переезд",
        note: "Заметка",
        video: "Видео",
        isRepeated: "Повторяющееся событие",

        period: {
            label: "Повторять",
            D: "ежедневно",
            W: "еженедельно",
            M: "ежемесячно",
            Y: "ежегодно",
        },
        days: {
            label: "По дням недели",
            0: "Пн",
            1: "Вт",
            2: "Ср",
            3: "Чт",
            4: "Пт",
            5: "Сб",
            6: "Вс",
        },
        every: {
            label: "Каждый/каждые",
            D: "дн",
            W: "нед",
            M: "мес",
            Y: "г",
        },
        endType: {
            label: "Завершить",
            D: "До определенной даты",
            C: "После нескольких повторений",
        },
        endOnDate: {
            label: "Дата завершения",
        },
        endOnCount: {
            label: "Количество повторов",
        },
        description: "Описание",
        descriptionPlaceholder: "...",

    },
    en: {
        toolbar: {
            title: "Record",
            delete: "Delete",
            deleteFuture: "Delete future repeats",
            deleteAll: "Delete all",
            close: "Close",
            settings: "Settings",
            save: "Save",
        },
        type: "Record type",
        restDay: "Rest day",
        sickness: "Sickness",
        vitamins: "Supplements",
        warning: "Problem",
        female: "Female cycle",
        diet: "Diet",
        bar: "Disruption",
        travel: "Travel",
        note: "Note",
        video: "Video",
        isRepeated: "Повторяющееся событие",

        period: {
            label: "Frequency",
            D: "Daily",
            W: "Weekly",
            M: "Monthly",
            Y: "Yearly",
        },
        days: {
            label: "On",
            0: "Mo",
            1: "Tu",
            2: "We",
            3: "Th",
            4: "Fr",
            5: "Sa",
            6: "Su",
        },
        every: {
            label: "Every",
            D: "d",
            W: "w",
            M: "m",
            Y: "y",
        },
        endType: {
            label: "End repeat",
            D: "On date",
            C: "After",
        },
        endOnDate: {
            label: "End date",
        },
        endOnCount: {
            label: "Number of repeats",
        },
        description: "Description",
    },
};