export const _MEASURE_TRANSLATE = {
    ru: {
        // Единицы измерения
        km: "км",
        meter: "м",
        mile: "ми",
        yard: "ярд",
        kmph: "км/ч",
        minpkm: "/км",
        minp100m: "/100м",
        minp500m: "/500м",
        minpml: '/ми',
        bpm: "уд/мин",
        min: "мин",
        h: 'ч',
        watt: "вт",
        percent: "%",
        tl: "",
        kkal: "ккал",
        vampkg: "вт/кг",
        kg: "кг",
        sm: "см",
        none: "",
        mh: "м/ч", // добавил - "метров в час". Это для VAM.
        spl: 'гребков',

        // Показатели
        adjustedPower: "Мощность корр",
        adjustedSpeed: "Темп корр",
        altitude: "Высота",
        cadence: "Каденс",
        calories: "Калории",
        distance: "Расстояние",
        duration: "Время",
        efficiencyFactor: "ФЭфф",
        elapsedDuration: "Время всего",
        elevation: "Набор",
        elevationGain: "Набор высоты",
        elevationLoss: "Сброс высоты",
        grade: "Градиент",
        heartRate: "Пульс",
        intensityLevel: "IL",
        movingDuration: "Время в движ",
        power: "Мощность",
        powerDecoupling: "Мощн:ЧСС",
        pace: 'Темп',
        speed: "Скорость",
        speedDecoupling: "Темп:ЧСС",
        trainingLoad: "TL",
        vam: "ВертикСкорость",
        vamPowerKg: "ОтноситМощность",
        variabilityIndex: "Индекс изменений",
        period: "Дата",
        percentComplete: "Процент выполнения",
        peaks: "Пики",
        peak: "Пик",
        day: "День",
        days: "День",
        week: "Нед",
        month: "Мес",
        quarter: 'Кв-л',
        plan: "План",
        actual: "Факт",
        mesocycle: "Мезоцикл",
        heartRateZone: 'Зоны пульса',
        speedZone: 'Зоны скорости/темпа',
        powerZone: 'Зоны мощности',
        zone: 'Зона',
        timeInZone: 'Время в зонах',

        //
        FTP: "ПАНО",
        ATP: "АэП",
        minValue: "Минимум",
        maxValue: "Максимум",

        // Запись календаря Измерение
        weight: "Вес",
        height: "Рост",
        waterPercent: "Вода(%)",
        percentFat: "Жир(%)",
        musculeMass: "Масса мышц(кг)",
        pulse: "Пульс покоя",
        pulseCost: 'Пульсовая стоимость',
        orthostaticPulse: 'Ортостатическая проба',
        sleepQuality: "Качество сна",
        sleepHours: "Часов сна",
        overallFeeling: "Общее состояние",

        // пики по времени
        '02sec': '2 cек',
        '05sec': '5 сек',
        '10sec': '10 сек',
        '12sec': '12 сек',
        '20sec': '20 сек',
        '30sec': '30 сек',
        '01min': '1 мин',
        '05min': '5 мин',
        '06min': '6 мин',
        '10min': '10 мин',
        '12min': '12 мин',
        '20min': '20 мин',
        '30min': '30 мин',
        '60min': '60 мин',
        '90min': '90 мин',

        // Для аналитики

        durationAvg: 'Сред. / {{seriesDateTrunc | translate | lowercase}}',
        durationTotal: 'Всего',
        durationMax: 'Макс. / {{seriesDateTrunc | translate | lowercase}}',

        distanceTotal: 'Всего',
        distanceAvg: 'Сред. / {{seriesDateTrunc | translate | lowercase}}',
        distanceMax: 'Макс. / {{seriesDateTrunc | translate | lowercase}}',


        runSum: 'Бег',
        bikeSum: 'Велосипед',
        swimSum: 'Плавание',


        fatigue: 'Усталость',
        fitness: 'Фитнес',
        form: 'Форма',
        fitnessStart: 'Фитнес',
        fitnessEnd: 'Фитнес',
        fatigueEnd: 'Усталость',
        formEnd: 'Форма',

        tlAvg: 'TL ср.',
        tlSum: 'TL всего',
        ilAvg: 'IL ср.',

        heartRate1minPeak: '1 мин',
        heartRate5minPeak: '5 мин',
        heartRate10minPeak: '10 мин',

        power1minPeak: '1 мин',
        power5minPeak: '5 мин',
        power10minPeak: '10 мин',

        previousPeriod: 'Предыдущее значение',
        currentPeriod: 'Текущее значение',
        athlete: "Спортсмен",
        activityType: "Вид спорта",

        run: 'Бег',
        swim: 'Плавание',
        bike: 'Велосипед',
        strength: 'Силовая тренировка',
        ski: 'Лыжи',
        rowing: 'Гребля',
        other: 'Прочее',
        transition: 'Транзитка',
        fuctionalTest: 'Функциональный тест',
        triathlon: 'Триатлон'


    },
    en: {

        // Единицы измерения
        km: "km",
        meter: "m",
        mile: "mi",
        yard: "yd",
        kmph: "km/h",
        minpkm: "/km",
        minp100m: "/100m",
        minp500m: "/500m",
        minpml: '/mi',
        bpm: "bpm",
        min: "min",
        h: 'h',
        watt: "Wt",
        percent: "%",
        tl: "",
        kkal: "kkal",
        vampkg: "wt/kg",
        kg: "kg",
        sm: "sm",
        none: "",
        mh: "m/h", // добавил - "метров в час". Это для VAM.
        spl: 'strokes',

        // Показатели
        adjustedPower: "APw",
        adjustedSpeed: "APc",
        altitude: "Altitude",
        cadence: "Cadence",
        calories: "Calories",
        distance: "Distancе",
        duration: "Duration",
        efficiencyFactor: "EF",
        elapsedDuration: "El. duration",
        elevation: "Elevation",
        elevationGain: "El. gain",
        elevationLoss: "El. loss",
        grade: "Grade",
        heartRate: "HR",
        intensityLevel: "IL",
        movingDuration: "Mov. duration",
        power: "Power",
        powerDecoupling: "Power:HR",
        pace: 'Pace',
        speed: "Speed",
        speedDecoupling: "Pace:HR",
        trainingLoad: "TL",
        vam: "VAM",
        vamPowerKg: "Relative power",
        variabilityIndex: "VI",
        period: "Date",
        percentComplete: "Complete percent",
        peaks: "Peaks",
        peak: "Peak",
        day: "Day",
        days: "Day",
        week: "Week",
        month: "Mon",
        quarter: 'Qtr',
        plan: "Plan",
        actual: "Actual",
        mesocycle: "Mesocycle",
        heartRateZone: 'Heart rate zone',
        speedZone: 'Speed/pace zone',
        powerZone: 'Power zone',
        zone: 'zone',
        timeInZone: 'Time in zone',

        //
        FTP: "LT",
        ATP: "AT",
        minValue: "Min",
        maxValue: "Max",

        // Запись календаря Измерение
        weight: "Weight",
        height: "Height",
        waterPercent: "Water(%)",
        percentFat: "Fat(%)",
        musculeMass: "Muscle mass(kg)",
        pulse: "Resting HR",
        pulseCost: 'Beats per km',
        orthostaticPulse: 'Orthostatic probe',
        sleepQuality: "Sleep quality",
        sleepHours: "Sleep hours",
        overallFeeling: "Overall feeling",

        // пики по времени
        '02sec': '2 sec',
        '05sec': '5 sec',
        '10sec': '10 sec',
        '12sec': '12 sec',
        '20sec': '20 sec',
        '30sec': '30 sec',
        '01min': '1 min',
        '05min': '5 min',
        '06min': '6 min',
        '10min': '10 min',
        '12min': '12 min',
        '20min': '20 min',
        '30min': '30 min',
        '60min': '60 min',
        '90min': '90 min',


        // для Аналитики

        durationAvg: 'Avg / {{seriesDateTrunc | translate | lowercase}}',
        durationTotal: 'Total',
        durationMax: 'Max / {{seriesDateTrunc | translate | lowercase}}',

        distanceTotal: 'Total',
        distanceAvg: 'Avg / {{seriesDateTrunc | translate | lowercase}}',
        distanceMax: 'Max / {{seriesDateTrunc | translate | lowercase}}',


        runSum: 'Running',
        bikeSum: 'Cycling',
        swimSum: 'Swimming',

        fatigue: 'Fatigue',
        fitness: 'Fitness',
        form: 'Form',
        fitnessStart: 'Fitness',
        fitnessEnd: 'Fitness',
        fatigueEnd: 'Fatigue',
        formEnd: 'Form',

        tlAvg: 'TL avg',
        tlSum: 'TL total',
        ilAvg: 'IL avg',

        heartRate1minPeak: '1 min',
        heartRate5minPeak: '5 min',
        heartRate10minPeak: '10 min',

        power1minPeak: '1 min',
        power5minPeak: '5 min',
        power10minPeak: '10 min',

        previousPeriod: 'Previous value',
        currentPeriod: 'Current value',
        athlete: "Athlete",
        activityType: "Sport",

        run: 'Running',
        swim: 'Swimming',
        bike: 'Cycling',
        strength: 'Strength training',
        ski: 'Skiing',
        other: 'Other',
        rowing: 'Rowing',
        transition: 'Transition',
        fuctionalTest: 'Functional test',
        triathlon: 'Triathlon'

    },
};
