export const _MEASURE_TRANSLATE = {
    ru: {
        // Единицы измерения
        km: "км",
        meter: "м",
        mile: "ми",
        yard: "ярд",
        kmph: "км/ч",
        minpkm: "/км",
        minp100m: "/100м",
        minp500m: "/500м",
        minpml: '/ми',
        bpm: "уд/мин",
        min: "мин",
        watt: "вт",
        percent: "%",
        tl: "",
        kkal: "ккал",
        vampkg: "вт/кг",
        kg: "кг",
        sm: "см",
        none: "",
        mh: "м/ч", // добавил - "метров в час". Это для VAM.
        spl: 'гребков',

        // Показатели
        adjustedPower: "Мощность корр",
        adjustedSpeed: "Темп корр",
        altitude: "Высота",
        cadence: "Каденс",
        calories: "Калории",
        distance: "Расстояние",
        duration: "Время",
        efficiencyFactor: "ФЭфф",
        elapsedDuration: "Время всего",
        elevation: "Набор",
        elevationGain: "Набор высоты",
        elevationLoss: "Сброс высоты",
        grade: "Градиент",
        heartRate: "Пульс",
        intensityLevel: "IL",
        movingDuration: "Время в движ",
        power: "Мощность",
        powerDecoupling: "Мощн:ЧСС",
        speed: "Темп/Скорость",
        speedDecoupling: "Темп:ЧСС",
        trainingLoad: "TL",
        vam: "ВертикСкорость",
        vamPowerKg: "ОтноситМощность",
        variabilityIndex: "Индекс изменений",

        //
        FTP: "ПАНО",
        ATP: "АэП",
        minValue: "Минимум",
        maxValue: "Максимум",

        // Запись календаря Измерение
        weight: "Вес",
        height: "Рост",
        waterPercent: "Вода(%)",
        percentFat: "Жир(%)",
        musculeMass: "Масса мышц(кг)",
        pulse: "Пульс покоя",
        pulseCost: 'Пульсовая стоимость',
        orthostaticPulse: 'Ортостатическая проба',
        sleepQuality: "Качество сна",
        sleepHours: "Часов сна",
        overallFeeling: "Общее состояние"

    },
    en: {

        // Единицы измерения
        km: "km",
        meter: "m",
        mile: "mi",
        yard: "yd",
        kmph: "km/h",
        minpkm: "/km",
        minp100m: "/100m",
        minp500m: "/500m",
        minpml: '/mi',
        bpm: "bpm",
        min: "min",
        watt: "Wt",
        percent: "%",
        tl: "",
        kkal: "kkal",
        vampkg: "wt/kg",
        kg: "kg",
        sm: "sm",
        none: "",
        mh: "m/h", // добавил - "метров в час". Это для VAM.
        spl: 'strokes',

        // Показатели
        adjustedPower: "APw",
        adjustedSpeed: "APc",
        altitude: "Altitude",
        cadence: "Cadence",
        calories: "Calories",
        distance: "Distancе",
        duration: "Duration",
        efficiencyFactor: "EF",
        elapsedDuration: "El. duration",
        elevation: "Elevation",
        elevationGain: "El. gain",
        elevationLoss: "El. loss",
        grade: "Grade",
        heartRate: "HR",
        intensityLevel: "IL",
        movingDuration: "Mov. duration",
        power: "Power",
        powerDecoupling: "Power:HR",
        speed: "Pace/Speed",
        speedDecoupling: "Pace:HR",
        trainingLoad: "TL",
        vam: "VAM",
        vamPowerKg: "Relative power",
        variabilityIndex: "VI",

        //
        FTP: "LT",
        ATP: "AT",
        minValue: "Min",
        maxValue: "Max",

        // Запись календаря Измерение
        weight: "Weight",
        height: "Height",
        waterPercent: "Water(%)",
        percentFat: "Fat(%)",
        musculeMass: "Muscle mass(kg)",
        pulse: "Resting HR",
        pulseCost: 'Beats per km',
        orthostaticPulse: 'Orthostatic probe',
        sleepQuality: "Sleep quality",
        sleepHours: "Sleep hours",
        overallFeeling: "Overall feeling",

    },
};
