export const translateGeneral = {
    ru: {
        staminity: "Staminity",
        application: {
            url: '',
            name: '',
            description: '',
        },
        ru: 'Русский',
        en: 'English',
        true: "Да",
        false: "Нет",
        week: "По неделям",
        day: "По дням",
        month: "По месяцам",
        quarter: "По кварталам",
        menu: 'Меню',
        updateToast: {
            message: "Перезагрузите страницу, чтобы загрузить обновление сервиса Staminity",
            action: "ПЕРЕЗАГРУЗИТЬ",
        },
        RUB: 'руб.',
        EUR: 'EUR',
        USD: 'USD',
        onlyBasicTariff: 'Подключить тариф',
        incompleteProfile: 'Не заполнен профиль',
        premiumExpireIn: 'Премиум: осталось {{days}} дн',
        coachExpireIn: 'Тренер: осталось {{days}} дн',
        clubExpireIn: 'Клуб: осталось {{days}} дн',
        expiredPremium: 'Премиум отключен',
        expiredCoach: 'Тренер отключен',
        expiredClub: 'Клуб отключен',
        loading: 'Загрузка...',
        pullToRefresh: 'Потяните для обновления',
        next: 'Далее',
        done: 'Готово'
    },
    en: {
        staminity: "Staminity",
        ru: 'Русский',
        en: 'English',
        true: "Yes",
        false: "No",
        week: "Week",
        day: "Day",
        month: "Month",
        quarter: "Quarter",
        menu: 'Menu',
        updateToast: {
            message: "Staminity update is available. Please refresh the browser page",
            action: "REFRESH",
        },
        RUB: 'RUB',
        EUR: 'EUR',
        USD: 'USD',
        onlyBasicTariff: 'Add tariff',
        incompleteProfile: 'Incomplete profile',
        premiumExpireIn: 'Premium: {{days | number}} days left',
        coachExpireIn: 'Coach: {{days | number}} days left',
        clubExpireIn: 'Club: {{days | number}} days left',
        expiredPremium: 'Premium expired',
        expiredCoach: 'Coach expired',
        expiredClub: 'Club expired',
        loading: 'Loading...',
        pullToRefresh: 'Pull to refresh',
        next: 'Next',
        done: 'Done'
    },
};

export const translateForm = {
    ru: {
        required: "Поле обязательно к заполнению",
        rangeNum: "Укажите значение в диапазоне от {{min}} до {{max}}",
        rangeStr: "Укажите текст от {{min}} до {{max}} символов",
        cancel: "Отменить",
        save: "Сохранить",
        invalidDate: "Некорректный формат даты",
        delete: "Удалить",
        edit: 'Изменить'
    },
    en: {
        required: "Mandatory field",
        rangeNum: "The value should be between {{min}} and {{max}}",
        rangeStr: "The length of text should be between {{min}} and {{max}} letters",
        cancel: "Cancel",
        save: "Save",
        invalidDate: "Incorrect date format",
        delete: "Delete",
        edit: 'Edit'
    },
};
