/*
 * В переводах нотифкаций используется фильтры пересчета показателей -
 * masureCalc, вывода единиц измерения - measureCalc translate для перевода
 * единиц измререния на установленный в сессии пользователя язык интерфейса
 *
 * Фильтры - это функции форматирования вывода. Они берут значение на вход,
 * пересчитывают и возвращают измененное значение.
 *
 * Конструкция "вход" | "название_фильтра":["параметр"...]. Фильтры могут
 * идти следом друг за дргуом передавая рассчитанное значение на вход следующему
 * фильтру
 *
 * При добавлении новых уведомлений необходимо создавать строку для последующего тестированию данного шаблона. Пример см. в notificationTestMessage
 * */
export const translateNotification = {
    ru: {
        notifications: 'Уведомления',
        title: 'Уведомления',

        activityCompletedByAthlete: "Выполнена тренировка {{data[1] | date:'short'}} \n {{'sport.'+data[0] | translate}}, {{data[4] | measureCalc:data[0]:'distance'}} {{'distance' | measureUnit:data[0] | translate}}, {{data[3] | measureCalc:data[0]:'duration'}}",
        activityCompletedByFollowing: "activityCompletedByFollowing",
        activityCompletedByFriend: "activityCompletedByFriend",
        activityCreatedByAthlete: "Спортсмен создал тренировку: {{'sport.'+data[1] | translate}}, {{data[2] | date:'short'}}, {{'category.'+data[4] | translate}}",
        activityCreatedByCoach: "Создана плановая тренировка: {{'sport.'+data[1] | translate}}, {{data[2] | date:'short'}}, {{'category.'+data[4] | translate}}",
        activityDeletedByAthlete: "Удалена тренировка спортсменом: {{'sport.'+data[1] | translate}}, {{data[2] | date:'short'}}, {{'category.'+data[4] | translate}}",
        activityDeletedByCoach: "Удалена тренировка: {{'sport.'+data[1] | translate}}, {{data[2] | date:'short'}}, {{'category.'+data[4] | translate}}",
        activityFactModifiedByAthlete: "Изменен факт в тренировке: {{'sport.'+data[1] | translate}}, {{data[2] | date:'short'}}, {{'category.'+data[4] | translate}}",
        activityModifiedByCoach: "Изменен план в тренировке: {{'sport.'+data[1] | translate}}, {{data[2] | date:'short'}}, {{'category.'+data[4] | translate}}",
        agentAccountEnabled: "Ваш аккаунт для юридического лица {{data[0]}} подтвержден. Теперь вы можете публиковать платные тренировочные планы в магазине",
        agentBindCardFailure: "Ошибка добавления новой карты! Карта {{data[0]}} не была добавлена в ваш {{data[1]}} аккаунт. Ошибка: {{data[2]}}",
        agentBindCardSuccess: "Карта {{data[0]}} добавлена для вывода средств в {{data[1]}}",
        agentFreeWithdrawalAcquired: "Ваш баланс достиг беспроцентного лимита для вывода средств. Сумма: {{data[0]}} {{data[1]}}. Выводите средства без комиссий!",
        agentWithdrawalApproved: "Поручение на вывод средств одобрено! Сумма вывода: {{data[0]}}{{data[1]}}, сумма к зачислению с учетом комиссии: {{data[2]}}{{data[3]}}",
        agentWithdrawalCompleted: "Поручение на вывод средств выполнено! Сумма вывода: {{data[0]}}{{data[1]}}, сумма зачисления с учетом комиссии: {{data[2]}}{{data[3]}}",
        agentWithdrawalDeclined: "Поручение на вывод средств отклонено! Запрошенная сумма: {{data[0]}}{{data[1]}}, причина отказа: {{data[2]}}",
        badUsernameOrPassword: "Невозможно подключить синхронизацию, неверное имя/пароль. ",
        billExpiredPaymentReceived: "Спасибо! Ваш платеж по счету на {{data[0]}} {{data[1]}} получен",
        billPayment_Failure_multiTariff: "Не удалось оплатить счет по вашим тарифам на {{data[3]}} {{data[4]}}. Попробуйте еще раз",
        billPayment_Failure_singleTariff: "Не удалось оплатить счет по тарифу {{data[0] | translate}} на {{data[3]}} {{data[4]}}. Попробуйте еще раз",
        billPayment_multiTariff: "Вы оплатили счет на {{data[2]}} {{data[3]}}. Срок действия подключенных тарифов продлен до {{data[1] | date:'shortDate'}}",
        billPayment_multiTariff_ZeroAmount: "Дополнительных начислений по вашим тарифам нет. Тарифы продлены до {{data[1] | date:'shortDate'}}",
        billPayment_singleTariff: "Вы оплатили счет на {{data[2]}} {{data[3]}}. Тариф {{data[0] | translate}} продлен до {{data[1] | date:'shortDate'}}",
        billPayment_singleTariff_ZeroAmount: "Дополнительных начислений по тарифу {{data[0] | translate}} нет. Тариф продлен до {{data[1] | date:'shortDate'}}",
        clubAthleteConnected: "У вас новый спортсмен в клубе: {{data[0]}}",
        clubAthleteDisconnected: "От вас отключен спортсмен: {{data[0]}}",
        clubCoachAssigned: "У вас новый тренер в клубе: {{data[0]}}",
        clubCoachRemoved: "От вас отключен тренер в клубе: {{data[0]}}",
        clubEnvCreate: "Для вас создан клуб {{data[0]}}. Клубный раздел доступен в левом меню",
        clubEnvDeleted: "Ваш клуб удален, спортсмены и тренеры клуба отключены от клуба",
        clubEnvDeleteInSomeDays: "Ваш клуб будет удален через 5 дней, все спортсмены и тренеры будут отключены от клуба. Подключите тариф, чтобы этого избежать",
        clubRoleAssigned: "Вам в клубе присвоена роль {{data[2] | translate}}",
        clubRoleRemoved: "В клубе вам отключена роль {{data[2] | translate}}",
        coachEnvDeleted: "Связь с вашими личными спортсменами удалена, т.к. тариф Тренер был отключен месяц назад",
        coachEnvDeleteInSomeDays: "Через 5 дней будет удалена связь со спортсменами, подключенными к вам напрямую, т.к. тариф Тренер был отключен 25 дней назад. Подключите тариф, чтобы этого избежать",
        competitionCreatedByAthlete: "Ученик запланировал соревнование: {{'sport.'+data[1] | translate}}, {{'type.'+data[2] | translate}}, priority: {{data[3]}}, {{data[4] | date:'short'}}",
        competitionCreatedByCoach: "Тренер запланировал соревнование: {{'sport.'+data[1] | translate}}, {{'type.'+data[2] | translate}}, priority: {{data[3]}}, {{data[4] | date:'short'}}",
        competitionDeletedByAthlete: "Ученик удалил соревнование: {{'sport.'+data[1] | translate}}, {{'type.'+data[2] | translate}}, priority: {{data[3]}}, {{data[4] | date:'short'}}",
        competitionDeletedByCoach: "Тренер удалил соревнование: {{'sport.'+data[1] | translate}}, {{'type.'+data[2] | translate}}, priority: {{data[3]}}, {{data[4] | date:'short'}}",
        competitionModifiedByAthlete: "Ученик изменил соревнование: {{'sport.'+data[1] | translate}}, {{'type.'+data[2] | translate}}, priority: {{data[3]}}, {{data[4] | date:'short'}}",
        competitionModifiedByCoach: "Тренер изменил соревнование: {{'sport.'+data[1] | translate}}, {{'type.'+data[2] | translate}}, priority: {{data[3]}}, {{data[4] | date:'short'}}",
        disabledCoachByClub: "Вам временно отключен тариф Тренер, подключенный клубом. Ожидается оплата от клуба",
        disabledPremiumByClub: "Вам временно отключен тариф Премиум, подключенный клубом. Ожидается оплата от клуба",
        disabledPremiumByCoach: "Вам временно отключен тариф Премиум, подключенный тренером. Ожидается оплата от тренера",
        enabledCoachByClub: "Вам снова доступны функции по тарифу Тренер, подключенному клубом",
        enabledPremiumByClub: "Вам снова доступны функции по тарифу Премиум, подключенному клубом",
        enabledPremiumByCoach: "Вам снова доступны функции по тарифу Премиум, подключенному тренером",
        expireTariffPurchase: "Срок действия тарифа {{data[0] | translate}} истекает {{data[1] | date:'shortDate'}}",
        expireTariffPurchaseToday: "Срок действия тарифа {{data[0] | translate}} истекает сегодня",
        expireTariffPurchaseYesterday: "Тариф {{data[0] | translate}} отключен",
        initialProviderSyncCompleted: "Начальная синхронизация завершена.\n Загружено {{data[0]}} из {{data[1]}} тренировок c {{data[2] | date:'short'}}",
        inviteJoinAthletes: "Тренер отправил вам приглашение в Стаминити и предлагает подключиться к нему",
        inviteJoinAthletesApproved: "Ваше приглашение принято, к вам подключен новый ученик",
        inviteJoinAthletesCancelled: "Тренер отменил приглашение присоединиться к нему",
        inviteJoinAthletesDeclined: "Ученик отклонил приглашение",
        inviteJoinClubMembers: "Вы получили приглашение вступить в клуб в Стаминити",
        inviteJoinClubMembersApproved: "Ваш запрос принят, в клуб добавлен новый член клуба",
        inviteJoinClubMembersCancelled: "Клуб отменил свое приглашение",
        inviteJoinClubMembersDeclined: "Ваше приглашение на вступление в клуб отклонено пользователем",
        joinClubAthletesByAdmin: "{{data[2]}} включен в число спортсменов клуба {{data[0]}}",
        joinClubAthletesByMember: "Включил себя в число спортсменов клуба {{data[0]}}",
        joinClubChiefCoachesByAdmin: "{{data[2]}} назначен главным тренером клуба {{data[0]}}",
        joinClubChiefCoachesByMember: "Назначил себя главным тренером клуба {{data[0]}}",
        joinClubCoachesByAdmin: "{{data[2]}} назначен тренером клуба {{data[0]}}",
        joinClubCoachesByMember: "Назначил себя тренером клуба {{data[0]}}",
        joinClubConsultingByAdmin: "{{data[2]}} назначен консультантом клуба {{data[0]}}",
        joinClubConsultingByMember: "Назначил себя консультантом клуба {{data[0]}}",
        joinClubManagementByAdmin: "{{data[2]}} назначен администратором клуба {{data[0]}}",
        joinCoachAthleteByAdmin: "Назначен тренер для спортсмена в клубе {{data[0]}}:\n Тренер: {{data[4]}}, спортсмен: {{data[2]}}",
        joinCoachByClub: "Вам подключен тариф Тренер за счет клуба",
        joinCoachByClubByAdmin: "{{data[2]}} подключен тариф 'Тренер' за счет клуба {{data[0]}}",
        joinCoachByClubByMember: "Подключил себе тариф 'Тренер' за счет клуба {{data[0]}}",
        joinPremiumByClub: "Вам подключен тариф 'Премиум' за счет клуба",
        joinPremiumByClubByAdmin: "{{data[2]}} подключен тариф 'Премиум' за счет клуба {{data[0]}}",
        joinPremiumByClubByMember: "Подключил себе тариф 'Премиум' за счет клуба {{data[0]}}",
        joinPremiumByCoach: "Вам подключен тариф 'Премиум' за счет тренера",
        leaveAthletesByAdmin: "Тренер исключил вас из списка своих спортсменов",
        leaveAthletesByMember: "Спортсмен отключился от вас",
        leaveClubAthletesByAdmin: "{{data[2]}} отключена роль 'Спортсмен' клуба {{data[0]}}",
        leaveClubAthletesByMember: "Администратор клуба отключил себе роль 'Спортсмен' в клубе {{data[0]}}",
        leaveClubChiefCoachesByAdmin: "{{data[2]}} отключена роль 'Главный тренер' клуба {{data[0]}}",
        leaveClubChiefCoachesByMember: "Администратор клуба отключил себе роль 'Главный тренер' в клубе {{data[0]}}",
        leaveClubCoachesByAdmin: "{{data[2]}} отключена роль 'Тренер' клуба {{data[0]}}",
        leaveClubCoachesByMember: "Администратор клуба отключил себе роль 'Тренер' в клубе {{data[0]}}",
        leaveClubConsultingByAdmin: "{{data[2]}} отключена роль 'Консультант' клуба {{data[0]}}",
        leaveClubConsultingByMember: "Администратор клуба отключил себе роль 'Консультант' в клубе {{data[0]}}",
        leaveClubManagementByAdmin: "{{data[2]}} отключена роль 'Администратор' клуба {{data[0]}}",
        leaveClubMembersByAdmin: "Вы отключены от клуба",
        leaveClubMembersByMember: "Член клуба покинул клуб",
        leaveClubMembersByOtherAdmin: "{{data[0]}} отключен от клуба {{data[2]}}",
        leaveCoachAthleteByAdmin: "Отключен тренер от спортсмена в клубе {{data[0]}}:\n Тренер: {{data[4]}}, спортсмен: {{data[2]}}",
        leaveCoachByClub: "Вам отключен тариф 'Тренер', ранее подключенный за счет клуба",
        leaveCoachByClubByAdmin: "{{data[2]}} отключен тариф 'Тренер' за счет клуба {{data[0]}}",
        leaveCoachByClubByMember: "Отключил себе тариф 'Тренер' за счет клуба {{data[0]}}",
        leavePremiumByClub: "Вам отключен тариф 'Премиум', ранее подключенный за счет клуба",
        leavePremiumByClubByAdmin: "{{data[2]}} отключен тариф 'Премиум' за счет клуба {{data[0]}}",
        leavePremiumByClubByMember: "Отключил себе тариф 'Премиум' за счет клуба {{data[0]}}",
        leavePremiumByCoach: "Вам отключен тариф 'Премиум', ранее подключенный за счет тренера",
        leaveUserGroupByAdmin: "Вы исключены из группы",
        leaveUserGroupByMember: "Член группы покинул группу",
        leaveUserGroupByOtherAdmin: "{{data[0]}} исключен из группы {{data[2]}}",
        measurementCreatedByAthlete: "Ученик добавил измерение: {{data[1] | date:'short'}}",
        measurementDeletedByAthlete: "Ученик удалил измерение: {{data[1] | date:'short'}}",
        measurementModifiedByAthlete: "Ученик изменил измерение: {{data[1] | date:'short'}}",
        multipleBBill: "Задолженность по неоплаченным счетам составляет {{data[2]}} {{data[3]}}. Просьба оплатить",
        newAthleteComment: "Ваш спортсмен оставил комментарий в тренировке: {{'sport.'+data[1] | translate}}, {{data[2] | date:'short'}}, {{'category.'+data[4] | translate}}",
        newAthleteHeartRateFTPBySystem: "Предлагаем обновить ПАНО по пульсу для вашего спортсмена по итогам его тренировки. Новое значение: {{data[1] | measureCalc: data[0]: 'heartRate'}} {{'heartRate' | measureUnit:data[0] | translate}}",
        newAthletePaceFTPBySystem: "Предлагаем обновить ПАНО по темпу для вашего спортсмена по итогам его тренировки. Новое значение: {{data[1] | measureCalc: data[0]: 'speed'}} {{'speed' | measureUnit:data[0] | translate}}",
        newAthletePowerFTPBySystem: "Предлагаем обновить ПАНО по мощности для вашего спортсмена по итогам его тренировки. Новое значение: {{data[1] | measureCalc: data[0]: 'power'}} {{'power' | measureUnit:data[0] | translate}}",
        newCoachComment: "Ваш тренер оставил комментарий в тренировке: {{'sport.'+data[1] | translate}}, {{data[2] | date:'short'}}, {{'category.'+data[4] | translate}}",
        newHeartRateFTPBySystem: "Предлагаем обновить значение ПАНО по пульсу по виду спорта: {{'sport.'+data[0] | translate}}. Новое значение: {{data[1] | measureCalc: data[0]: 'heartRate'}} {{'heartRate' | measureUnit:data[0] | translate}}",
        newLikeSingle: "newLikeSingle",
        newMessages: "newMessages",
        newPaceFTPBySystem: "Предлагаем обновить значение ПАНО по темпу по виду спорта: {{'sport.'+data[0] | translate}}. Новое значение: {{data[1] | measureCalc: data[0]: 'speed'}} {{'speed' | measureUnit:data[0] | translate}}",
        newPowerFTPBySystem: "Предлагаем обновить значение ПАНО по мощности по виду спорта: {{'sport.'+data[0] | translate}}. Новое значение: {{data[1] | measureCalc: data[0]: 'power'}} {{'power' | measureUnit:data[0] | translate}}",
        newSingleMessage: "newSingleMessage",
        newUserComment: "newUserComment",
        newUserCommentsAndLikes: "newUserCommentsAndLikes",
        promoExpired: "promoExpired",
        promoExpireSoon: "promoExpireSoon",
        providerSyncError: "Подключение не удалось. Необходимо повторно настроить синхронизацию",
        recordCreatedByAthlete: "Ученик создал событие: {{data[1] | translate}}, {{data[3] | date:'short'}}",
        recordCreatedByCoach: "Тренер создал событие: {{data[1] | translate}}, {{data[3] | date:'short'}}",
        recordDeletedByAthlete: "Ученик удалил событие: {{data[1] | translate}}, {{data[3] | date:'short'}}",
        recordDeletedByCoach: "Тренер удалил событие: {{data[1] | translate}}, {{data[3] | date:'short'}}",
        recordModifiedByAthlete: "Ученик изменил событие: {{data[1] | translate}}, {{data[3] | date:'short'}}",
        recordModifiedByCoach: "Тренер изменил событие: {{data[1] | translate}}, {{data[3] | date:'short'}}",
        recurring_Failure_multiTariff: "Оплату по вашим тарифам по счету на {{data[2]}} {{data[3]}} выполнить не удалось. Оплатите счет вручную",
        recurring_Failure_singleTariff: "Оплату по тарифу {{data[0] | translate}} по счету на {{data[2]}} {{data[3]}} выполнить не удалось. Оплатите счет вручную",
        requestJoinAthletes: "Спортсмен отправил вам запрос на подключение в Staminity",
        requestJoinAthletesApproved: "Ваш запрос на подключение к тренеру одобрен",
        requestJoinAthletesCancelled: "Запрос на подключение к тренеру отменен отправителем",
        requestJoinAthletesDeclined: "Тренер отклонил ваш запрос на подключение",
        requestJoinClubMembers: "Вы получили новый запрос от пользователя на вступление в клуб",
        requestJoinClubMembersApproved: "Ваш запрос на вступление в клуб одобрен",
        requestJoinClubMembersApprovedByOthers: "{{data[0]}} принят в клуб {{data[2]}}",
        requestJoinClubMembersCancelled: "Запрос на подключение к клубу отменен отправителем",
        requestJoinClubMembersDeclined: "Ваш запрос на вступление в клуб отклонен",
        requestJoinClubMembersDeclinedByOthers: "{{data[0]}} не принят в клуб {{data[2]}}. Запрос отклонен",
        requestJoinFriendsApproved: "Ваш запрос на дружбу принят",
        requestJoinFriendsDeclined: "Ваш запрос на дружбу отклонен",
        requestJoinUserGroupApproved: "Ваш запрос на вступление в группу одобрен",
        requestJoinUserGroupDeclined: "Ваш запрос на вступление в группу отклонен",
        requestLeaveClubMembers: "Вы получили новый запрос от члена клуба на выход из клуба",
        requestLeaveClubMembersApproved: "Ваш запрос на выход из клуба одобрен. Вы исключены из клуба",
        requestLeaveClubMembersDeclined: "Ваш запрос на выход из клуба отклонен",
        singleBBill: "Выставлен счет #{{data[1]}} на {{data[2]}} {{data[3]}}. Просьба оплатить",
        singleFBill: "Для продолжения использования тарифа {{data[0] | translate}} оплатите счет #{{data[1]}} на {{data[2]}} {{data[3]}}",
        staminityNotification: "{{data[0]}}",
        tariffRecurringSuccess: "Оплата по тарифу {{data[0] | translate}} выполнена успешно. С вашей карты списано {{data[2]}} {{data[3]}}. Тариф продлен до {{data[1] | date:'shortDate'}}",
        tariffRecurringSuccessMulti: "Оплата по подключенным тарифам выполнена успешно. С вашей карты списано {{data[2]}} {{data[3]}}. Тарифы продлены до {{data[1] | date:'shortDate'}}",
        tariffRecurringTonight: "Приближается срок оплаты по тарифу {{data[0] | translate}}. {{data[1] | date:'shortDate'}} будет проведена попытка списания {{data[2]}} {{data[3]}}",
        tariffRecurringTonightMulti: "Приближается срок оплаты по подключенным тарифам. {{data[1] | date:'shortDate'}} будет проведена попытка списания {{data[2]}} {{data[3]}}",
        trainingPlanPurchased: "Ваш тренировочный план {{data[0]}} купили, поздравляем! Сумма покупки: {{data[1]}} {{data[2]}}",
        trainingPlanPurchasedFree: "Ваш тренировочный план {{data[0]}} подключен бесплатно пользователем в Staminity",
        trainingPlanPurchaseFailed: "Ошибка оплаты плана {{data[0]}}. Причина: {{data[1]}}",
        trainingPlanPurchaseSuccess: "Поздравляем! Вы успешно приобрели тренировочный план {{data[0]}} от {{data[1]}}",
        trialExpired: "Закончился пробный период по тарифу {{data[0] | translate}}",
        trialExpiredAfterOldTariff: "Закончился пробный период по тарифу {{data[0] | translate}}. С сегодняшнего дня тариф подключен на платной основе, начисления производятся ежедневно в рамках существующего счета",
        trialExpireInSomeDays: "Пробный период по тарифу {{data[0] | translate}} завершается {{data[1] | date:'shortDate'}}",
        trialExpireInSomeDaysAfterOldTariff: "Пробный период по тарифу {{data[0] | translate}} завершается {{data[1] | date:'shortDate'}}. С {{data[2] | date:'shortDate'}} тариф будет подключен на платной основе с ежедневными начислениями",
        trialExpireToday: "Пробный период по тарифу {{data[0] | translate}} закончится сегодня",
        trialExpireTodayAfterOldTariff: "Сегодня завершается пробный период по тарифу {{data[0] | translate}}. С {{data[2] | date:'shortDate'}} тариф будет подключен на платной основе с ежедневными начислениями",
        uploadActivityByProvider: "Загружена тренировка {{data[1] | date:'short'}} \n {{'sport.'+data[0] | translate}}, {{data[4] | measureCalc:data[0]:'distance'}} {{'distance' | measureUnit:data[0] | translate}}, {{data[3] | measureCalc:data[0]:'duration'}}",
        zonesChangedByAthlete: "Ваш спортсмен изменил настройки тренировочных зон и пороговых значений",
        zonesChangedByCoach: "Изменены настройки ваших тренировочных зон и пороговых значений",

    },
//    ----------------- ENGLISH ---------------------

    en: {

        activityCompletedByAthlete: "Workout has been completed: {{data[1] | date:'short'}} \n {{'sport.'+data[0] | translate}}, {{data[4] | measureCalc:data[0]:'distance'}} {{'distance' | measureUnit:data[0] | translate}}, {{data[3] | measureCalc:data[0]:'duration'}}",
        activityCompletedByFollowing: "activityCompletedByFollowing",
        activityCompletedByFriend: "activityCompletedByFriend",
        activityCreatedByAthlete: "New workout created by your athlete: {{'sport.'+data[1] | translate}}, {{data[2] | date:'short'}}, {{'category.'+data[4] | translate}}",
        activityCreatedByCoach: "New planned workout: {{'sport.'+data[1] | translate}}, {{data[2] | date:'short'}}, {{'category.'+data[4] | translate}}",
        activityDeletedByAthlete: "Workout deleted by your athlete: {{'sport.'+data[1] | translate}}, {{data[2] | date:'short'}}, {{'category.'+data[4] | translate}}",
        activityDeletedByCoach: "Deleted workout: {{'sport.'+data[1] | translate}}, {{data[2] | date:'short'}}, {{'category.'+data[4] | translate}}",
        activityFactModifiedByAthlete: "Workout has been changed by your athlete: {{'sport.'+data[1] | translate}}, {{data[2] | date:'short'}}, {{'category.'+data[4] | translate}}",
        activityModifiedByCoach: "Workout plan has been changed {{'sport.'+data[1] | translate}}, {{data[2] | date:'short'}}, {{'category.'+data[4] | translate}}",
        agentAccountEnabled: "Your legal entity account for company {{data[0]}} has been confirmed. Now you can publish paid training plans in the Store",
        agentBindCardFailure: "Attempt failed! New card {{data[0]}} has not been added to your {{data[1]}} account. Error message: {{data[2]}}",
        agentBindCardSuccess: "New card {{data[0]}} has been added. Now you can withdraw money from your {{data[1]}} account",
        agentFreeWithdrawalAcquired: "Your balance amount has reached the fee-free limit of withdrawal! Balance: {{data[0]}} {{data[1]}}. Withdraw without fees",
        agentWithdrawalApproved: "Your withdrawal request has been approved! Amount of withdrawal: {{data[0]}}{{data[1]}}, net amount after fees: {{data[2]}}{{data[3]}}",
        agentWithdrawalCompleted: "Your withdrawal request has been completed! Amount of withdrawal: {{data[0]}}{{data[1]}}, net amount after fees: {{data[2]}}{{data[3]}}",
        agentWithdrawalDeclined: "Your withdrawal request has been declined. Requested amount: {{data[0]}}{{data[1]}}. Comment: {{data[2]}}",
        badUsernameOrPassword: "Automatic upload set up has failed: wrong username or password",
        billExpiredPaymentReceived: "Thank you! Your {{data[0]}} {{data[1]}} payment has been processed",
        billPayment_Failure_multiTariff: "Your {{data[3]}} {{data[4]}} payment for your tariffs has failed. Please try again",
        billPayment_Failure_singleTariff: "Something went wrong with your {{data[3]}} {{data[4]}} payment for {{data[0] | translate}} tariff. Please try again",
        billPayment_multiTariff: "You've successfully paid {{data[2]}} {{data[3]}} invoice. Your tariffs have been prolonged till {{data[1] | date:'shortDate'}}",
        billPayment_multiTariff_ZeroAmount: "There are no additional fees to be paid. Subscribtion has been prolonged till {{data[1] | date:'shortDate'}} ",
        billPayment_singleTariff: "You've successfully paid {{data[2]}} {{data[3]}} invoice. Your {{data[0] | translate}tariffs have been prolonged till {{data[1] | date:'shortDate'}}",
        billPayment_singleTariff_ZeroAmount: "There are no additional fees to be paid for your tariff {{data[0] | translate}}. Subscribtion has been prolonged till {{data[1] | date:'shortDate'}} ",
        clubAthleteConnected: "You have a new club athlete: {{data[0]}}",
        clubAthleteDisconnected: "{{data[0]}} have been removed from the list of your athletes",
        clubCoachAssigned: "Your new club coach is {{data[0]}}",
        clubCoachRemoved: "Your club coach {{data[0]}} has been disconnected from you",
        clubEnvCreate: "Club {{data[0]}} created. Club section is available in the menu to the left",
        clubEnvDeleted: "Your club has been deleted. All club members have been disconnected from the club",
        clubEnvDeleteInSomeDays: "Your club will be deleted in 5 days, all club members will be disconnected from it. To keep it please enable the Club tariff'",
        clubRoleAssigned: "Your new club role is {{data[2] | translate}}",
        clubRoleRemoved: "Your club role {{data[2] | translate}} has been removed",
        coachEnvDeleted: "All connections with your personal athletes have been terminated because the Coach tariff was disabled a month ago",
        coachEnvDeleteInSomeDays: "Your personal athletes will be disconnected from you in 5 days because the Coach tariff was disabled 25 days ago. To keep connections please enable the Coach tariff",
        competitionCreatedByAthlete: "Your athlete has created a new competition: {{'sport.'+data[1] | translate}}, {{'type.'+data[2] | translate}}, priority: {{data[3]}}, {{data[4] | date:'short'}}",
        competitionCreatedByCoach: "Your coach has created a new competition: {{'sport.'+data[1] | translate}}, {{'type.'+data[2] | translate}}, priority: {{data[3]}}, {{data[4] | date:'short'}}",
        competitionDeletedByAthlete: "Your athlete has deleted a competition: {{'sport.'+data[1] | translate}}, {{'type.'+data[2] | translate}}, priority: {{data[3]}}, {{data[4] | date:'short'}}",
        competitionDeletedByCoach: "Your coach has deleted a competition: {{'sport.'+data[1] | translate}}, {{'type.'+data[2] | translate}}, priority: {{data[3]}}, {{data[4] | date:'short'}}",
        competitionModifiedByAthlete: "Competition has been edited by your athlete: {{'sport.'+data[1] | translate}}, {{'type.'+data[2] | translate}}, priority: {{data[3]}}, {{data[4] | date:'short'}}",
        competitionModifiedByCoach: "Competition has been edited by the coach: {{'sport.'+data[1] | translate}}, {{'type.'+data[2] | translate}}, priority: {{data[3]}}, {{data[4] | date:'short'}}",
        disabledCoachByClub: "Your Coach tariff previously enabled by the club has been blocked temporarily. Payment from the club is awaited",
        disabledPremiumByClub: "Your Premium tariff previously enabled by the club has been blocked temporarily. Payment from the club is awaited",
        disabledPremiumByCoach: "Your Premium tariff previously enabled by the coach has been blocked temporarily. Payment from the coach is awaited",
        enabledCoachByClub: "Your Coach tariff has been enabled again by the club",
        enabledPremiumByClub: "Your Premium tariff has been enabled again by the club",
        enabledPremiumByCoach: "Your Premium tariff has been enabled again by the coach",
        expireTariffPurchase: "Your tariff {{data[0] | translate}} expires {{data[1] | date:'shortDate'}}",
        expireTariffPurchaseToday: "Your tariff {{data[0] | translate}} expires today",
        expireTariffPurchaseYesterday: "Your tariff {{data[0] | translate}} expired yesterday",
        initialProviderSyncCompleted: "Initial sync has been completed.\n {{data[0]}} from {{data[1]}} workouts uploaded from {{data[2] | date:'short'}}",
        inviteJoinAthletes: "Coach invites you to join him in Staminity",
        inviteJoinAthletesApproved: "Your invitation has been accepted, you have a new athlete",
        inviteJoinAthletesCancelled: "Coach has cancelled the invitation to join him",
        inviteJoinAthletesDeclined: "Your invitation has been declined by the athlete",
        inviteJoinClubMembers: "Club invites you to join it in Staminity",
        inviteJoinClubMembersApproved: "Your invitation has been accepted and new club member joined your club",
        inviteJoinClubMembersCancelled: "The club has cancelled the invitation to join it",
        inviteJoinClubMembersDeclined: "Your invitation to become club member has been declined by the user",
        joinClubAthletesByAdmin: "{{data[2]}} is now a club athlete in {{data[0]}}",
        joinClubAthletesByMember: "Agreed to become a club athlete in {{data[0]}}",
        joinClubChiefCoachesByAdmin: "{{data[2]}} became a head coach in {{data[0]}}",
        joinClubChiefCoachesByMember: "Assigned himself a role of a head coach in {{data[0]}}",
        joinClubCoachesByAdmin: "{{data[2]}} is a club coach now in {{data[0]}}",
        joinClubCoachesByMember: "Assigned himself a role of a club coach in {{data[0]}}",
        joinClubConsultingByAdmin: "{{data[2]}} is a club consultant in {{data[0]}}",
        joinClubConsultingByMember: "Assigned himself a role of a club consultant in {{data[0]}}",
        joinClubManagementByAdmin: "{{data[2]}} is a club admin now in {{data[0]}}",
        joinCoachAthleteByAdmin: "Coach {{data[4]}} has been assigned to the club athlete {{data[2]}} in club {{data[0]}}",
        joinCoachByClub: "The Club has enabled a Coach tariff for you",
        joinCoachByClubByAdmin: "{{data[2]}} has been subscribed to the Coach tariff at the expense of the club {{data[0]}}",
        joinCoachByClubByMember: "Subscribed himself to the Coach tariff at the expense of the club {{data[0]}}",
        joinPremiumByClub: "Congratulations! The Club has enabled a Premium tariff for you",
        joinPremiumByClubByAdmin: "{{data[2]}} has been subscribed to the Premium tariff at the expense of the club {{data[0]}}",
        joinPremiumByClubByMember: "Subscribed himself to the Premium tariff at the expense of the club {{data[0]}}",
        joinPremiumByCoach: "Congratulations! The Coach has enabled a Premium tariff for you",
        leaveAthletesByAdmin: "You've been disconnected from the coach",
        leaveAthletesByMember: "Your athlete has disconnected from you",
        leaveClubAthletesByAdmin: "Role 'Club athlete' has been removed for {{data[2]}} in club {{data[0]}}",
        leaveClubAthletesByMember: "Club admin has removed for himself the 'Club athlete' role in club {{data[0]}}",
        leaveClubChiefCoachesByAdmin: "Role 'Head coach' has been removed for {{data[2]}} in club {{data[0]}}",
        leaveClubChiefCoachesByMember: "Club admin has removed for himself the 'Head coach' role in club {{data[0]}}",
        leaveClubCoachesByAdmin: "Role 'Coach' has been removed for {{data[2]}} in club {{data[0]}}",
        leaveClubCoachesByMember: "Club admin has removed for himself the 'Coach' role in club{{data[0]}}",
        leaveClubConsultingByAdmin: "Role 'Consultant' has been removed for {{data[2]}} in club {{data[0]}}",
        leaveClubConsultingByMember: "Club admin has removed for himself the 'Consultant' role in club {{data[0]}}",
        leaveClubManagementByAdmin: "Role 'Administrator' has been removed for {{data[2]}} in club {{data[0]}}",
        leaveClubMembersByAdmin: "You've been disconnected from the club",
        leaveClubMembersByMember: "Club member has left the club",
        leaveClubMembersByOtherAdmin: "{{data[0]}} has been disconnected from {{data[2]}}",
        leaveCoachAthleteByAdmin: "Coach {{data[4]}} has been removed from the club athlete {{data[2]}} in club {{data[0]}}",
        leaveCoachByClub: "The Coach tariff previously enabled by the club has been disabled",
        leaveCoachByClubByAdmin: "The Coach tariff previously enabled by the club has been disabled for {{data[2]}}",
        leaveCoachByClubByMember: "Coach tariff previously enabled by the club has been disabled by the user",
        leavePremiumByClub: "The Premium tariff previously enabled by the club has been disabled",
        leavePremiumByClubByAdmin: "The Premium tariff previously enabled by the club has been disabled for {{data[2]}}",
        leavePremiumByClubByMember: "Premium tariff previously enabled by the club has been disabled by the user",
        leavePremiumByCoach: "The Premium tariff previously enabled by the coach has been disabled",
        leaveUserGroupByAdmin: "You've been removed from the group",
        leaveUserGroupByMember: "Group member has left the group",
        leaveUserGroupByOtherAdmin: "{{data[0]}} has been removed from {{data[2]}}",
        measurementCreatedByAthlete: "Measurement added by your athlete: {{data[1] | date:'short'}}",
        measurementDeletedByAthlete: "Measurement deleted by your athlete:{{data[1] | date:'short'}}",
        measurementModifiedByAthlete: "Measurement changed by your athlete: {{data[1] | date:'short'}}",
        multipleBBill: "You have unpaid invoices {{data[2]}} {{data[3]}}. Please make a payment",
        newAthleteComment: "New comment from your athlete in workout: {{'sport.'+data[1] | translate}}, {{data[2] | date:'short'}}, {{'category.'+data[4] | translate}}",
        newAthleteHeartRateFTPBySystem: "We've detected a new HR LT value for your athlete: {{data[1] | measureCalc: data[0]: 'heartRate'}} {{'heartRate' | measureUnit:data[0] | translate}}, sport: {{'sport.'+data[0] | translate}}. You may set up a new value in Settings.",
        newAthletePaceFTPBySystem: "We've detected a new Pace LT value for your athlete: {{data[1] | measureCalc: data[0]: 'speed'}} {{'speed' | measureUnit:data[0] | translate}}, sport: {{'sport.'+data[0] | translate}}. You may set up a new value in Settings.",
        newAthletePowerFTPBySystem: "We've detected a new Power LT value for your athlete: {{data[1] | measureCalc: data[0]: 'power'}} {{'power' | measureUnit:data[0] | translate}}, sport: {{'sport.'+data[0] | translate}}. You may set up a new value in Settings.s",
        newCoachComment: "New comment from your coach in workout: {{'sport.'+data[1] | translate}}, {{data[2] | date:'short'}}, {{'category.'+data[4] | translate}}",
        newHeartRateFTPBySystem: "New HR LT value: {{data[1] | measureCalc: data[0]: 'heartRate'}} {{'heartRate' | measureUnit:data[0] | translate}}, sport: {{'sport.'+data[0] | translate}}. Please change your settings",
        newLikeSingle: "newLikeSingle",
        newMessages: "newMessages",
        newPaceFTPBySystem: "New pace LT value: {{data[1] | measureCalc: data[0]: 'speed'}} {{'speed' | measureUnit:data[0] | translate}}, sport: {{'sport.'+data[0] | translate}}. Please change your settings",
        newPowerFTPBySystem: "New power LT value: {{data[1] | measureCalc: data[0]: 'power'}} {{'power' | measureUnit:data[0] | translate}}, sport: {{'sport.'+data[0] | translate}}. Please change your settings",
        newSingleMessage: "newSingleMessage",
        newUserComment: "newUserComment",
        newUserCommentsAndLikes: "newUserCommentsAndLikes",
        promoExpired: "promoExpired",
        promoExpireSoon: "promoExpireSoon",
        providerSyncError: "Sync error. Please check sync configuration",
        recordCreatedByAthlete: "New event created by the athlete: {{data[1] | translate}}, {{data[3] | date:'short'}}",
        recordCreatedByCoach: "New event created by the coach: {{data[1] | translate}}, {{data[3] | date:'short'}}",
        recordDeletedByAthlete: "Event has been deleted by your athlete: {{data[1] | translate}}, {{data[3] | date:'short'}}",
        recordDeletedByCoach: "Event has been deleted by the coach: {{data[1] | translate}}, {{data[3] | date:'short'}}",
        recordModifiedByAthlete: "Event has been edited by athlete: {{data[1] | translate}}, {{data[3] | date:'short'}}",
        recordModifiedByCoach: "Event has been edited by coach: {{data[1] | translate}}, {{data[3] | date:'short'}}",
        recurring_Failure_multiTariff: "Auto payment of the invoices {{data[2]}} {{data[3]}} has failed. To continue using your tariffs please check and pay unpaid invoices manually",
        recurring_Failure_singleTariff: "Auto payment of the invoice for {{data[0] | translate}} tariff on {{data[2]}} {{data[3]}} has failed. To continue using your tariff please check and pay the unpaid invoice manually",
        requestJoinAthletes: "New connection request from an athlete",
        requestJoinAthletesApproved: "Your connection request has been accepted by the coach",
        requestJoinAthletesCancelled: "Athlete has cancelled his connection request",
        requestJoinAthletesDeclined: "Coach has declined your connection request",
        requestJoinClubMembers: "You've received a new request to join the club",
        requestJoinClubMembersApproved: "Your request to join the club has been accepted",
        requestJoinClubMembersApprovedByOthers: "{{data[0]}} has joined the club {{data[2]}}",
        requestJoinClubMembersCancelled: "Incoming request to join the club has been cancelled by the sender",
        requestJoinClubMembersDeclined: "Your request to join the club has been declined",
        requestJoinClubMembersDeclinedByOthers: "Request to join the club from {{data[0]}} has been declined",
        requestJoinFriendsApproved: "Your friend request has been accepted",
        requestJoinFriendsDeclined: "Your friend request has been declined",
        requestJoinUserGroupApproved: "Your request to join the group has been accepted",
        requestJoinUserGroupDeclined: "Your request to join the group has been declined",
        requestLeaveClubMembers: "You've received a new request to leave the club",
        requestLeaveClubMembersApproved: "Your request to leave the club has been approved. You've been disconnected from the club",
        requestLeaveClubMembersDeclined: "Your request to leave the club has been declined",
        singleBBill: "Please pay {{data[2]}} {{data[3]}} invoice #{{data[1]}}. Check details in Settings - Invoices",
        singleFBill: "To continue using {{data[0] | translate}} tariff please pay {{data[2]}} {{data[3]}} invoice #{{data[1]}}",
        staminityNotification: "{{data[1]}}",
        tariffRecurringSuccess: "Your payment for {{data[0] | translate}} tariff has been successfully processed. Your card has been charged for {{data[2]}} {{data[3]}} and your tariff functions will be able till {{data[1] | date:'shortDate'}}",
        tariffRecurringSuccessMulti: "Your payment for your tariffs has been successfully processed. Your card has been charged for {{data[2]}} {{data[3]}} and your tariff's functions will be able till {{data[1] | date:'shortDate'}}",
        tariffRecurringTonight: "Your tariff {{data[0] | translate}} will be expired soon. {{data[1] | date:'shortDate'}} your card will be charged for {{data[2]}} {{data[3]}}",
        tariffRecurringTonightMulti: "Your tariffs will be expired soon. {{data[1] | date:'shortDate'}} your card will be charged for {{data[2]}} {{data[3]}}",
        trainingPlanPurchased: "Your training plan {{data[0]}} has been purchased. Amount: {{data[1]}} {{data[2]}}",
        trainingPlanPurchasedFree: "Your training plan {{data[0]}} has been used for free by a new user",
        trainingPlanPurchaseFailed: "Plan {{data[0]}} payment error: {{data[1]}}",
        trainingPlanPurchaseSuccess: "Congratulations! You've successfully purchased training plan '{{data[0]}}' by {{data[1]}}",
        trialExpired: "Trial period for {{data[0] | translate}} tariff has expired",
        trialExpiredAfterOldTariff: "Trial period for {{data[0] | translate}} tariff has expired. From today the cost of using this tariff will be added to your bill on daily basis",
        trialExpireInSomeDays: "Trial period for {{data[0] | translate}} tariff expires on {{data[1] | date:'shortDate'}}",
        trialExpireInSomeDaysAfterOldTariff: "Trial period for {{data[0] | translate}} tariff expires on {{data[1] | date:'shortDate'}}. From {{data[2] | date:'shortDate'}} the cost of using this tariff will be added to your invoice on daily basis",
        trialExpireToday: "Trial period for {{data[0] | translate}} tariff expires today",
        trialExpireTodayAfterOldTariff: "Trial period for {{data[0] | translate}} tariff expires today. From tomorrow the cost of using this tariff will be added to your invoice on daily basis",
        uploadActivityByProvider: "Workout from {{data[1] | date:'short'}} has been uploaded.\n {{'sport.'+data[0] | translate}}, {{data[4] | measureCalc:data[0]:'distance'}} {{'distance' | measureUnit:data[0] | translate}}, {{data[3] | measureCalc:data[0]:'duration'}}",
        zonesChangedByAthlete: "Your athlete has changed his training zones and/or lactate treshold values",
        zonesChangedByCoach: "Your training zones and/or lactate threshold have been changed by the coach",

    },
};
